<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>404 HTML Template by Colorlib</title>
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <style>
        * {
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
        }

        body {
            padding: 0;
            margin: 0;
        }

        #content {
            height: 70vh;
            min-height: 400px;
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 1000
        }

        #content-in {
            text-align: center;
            max-width: 1000px;
            color: #fff;
            display: block
        }

        h1 {
            font-family: 'Fredoka One', cursive;
            font-size: 100px;
            margin: 0 0 0.2em 0;
            color: #ff508e;
            text-transform: uppercase;
        }

        h2 {
            font-family: 'Raleway', sans-serif;
            font-size: 22px;
            font-weight: 400;
            text-transform: uppercase;
            line-height: 160%;
            color: #222;
            margin: 0 0 1em 0;
        }

        a {
            font-family: 'Raleway', sans-serif;
            display: inline-block;
            font-weight: 700;
            border-radius: 15px;
            text-decoration: none;
            color: #b081fa;
        }

        @media only screen and (max-width: 767px) {
            .notfound-404 h1 {
                font-size: 60px;
            }
        }
    </style>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div id="notfound">
    <div id="content">
        <div id="content-in">
            <h1><?php echo $message ?? $GLOBALS['message'] ?? 'Pracujeme'; ?></h1>
            <h2>
				<?php echo !empty($description) ? "<p>$description</p>" : 'Zrovna provádíme údržbu!<br>Zkuste to prosím za chvilku znovu.'; ?>
            </h2>
            <a href="">Obnovit stránku</a>
        </div>
    </div>
</div>
</body>
</html>
